# Generated by Django 4.1.7 on 2023-03-07 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldDataTypesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'data_types',
            },
        ),
        migrations.CreateModel(
            name='SchemaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_generated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('csv_file', models.FileField(blank=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_schemas',
            },
        ),
        migrations.CreateModel(
            name='SchemaFieldsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('data_field_name', models.CharField(max_length=255)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scv_generator.fielddatatypesmodel')),
                ('key_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scv_generator.schemamodel')),
            ],
            options={
                'db_table': 'schema_fields',
            },
        ),
        migrations.AddConstraint(
            model_name='schemafieldsmodel',
            constraint=models.UniqueConstraint(fields=('key_schema', 'order'), name='Integer ordering for each new schema'),
        ),
    ]
