# Generated by Django 4.1.7 on 2023-03-10 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv_generator', '0002_fieldssavedoptionsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaConfigsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('separator', models.CharField(choices=[('1', 'Comma (,)'), ('2', 'Semicolon (;)')], max_length=2)),
                ('string_character', models.CharField(choices=[('1', "Quote (')"), ('2', 'Double-quote (")')], max_length=2)),
                ('data_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scv_generator.dataschema')),
            ],
        ),
    ]
