# Generated by Django 4.1.7 on 2023-03-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scv_generator', '0003_schemaconfigsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldssavedoptionsmodel',
            name='options',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterModelTable(
            name='schemaconfigsmodel',
            table='configs_of_tables',
        ),
    ]
