MAILS_ENDINGS = ['yahoo.it', 'live.nl', 'yahoo.co.in', 'hetnet.nl', 'aliceadsl.fr', 'gmx.de', 'laposte.net', 'yahoo.in',
                 'aol.com', 'live.fr', 'arcor.de', 't-online.de', 'sbcglobal.net', 'gmail.com', 'msn.com',
                 'earthlink.net', 'yahoo.com.br', 'sfr.fr', 'live.com', 'mail.com', 'yahoo.co.jp', 'home.nl', 'qq.com',
                 'neuf.fr', 'bellsouth.net', 'facebook.com', 'mac.com', 'voila.fr', 'orange.fr', 'libero.it',
                 'hotmail.de', 'yahoo.de', 'ymail.com', 'skynet.be', 'hotmail.co.uk', 'sky.com', 'virgilio.it',
                 'tin.it', 'live.com.au', 'live.ca', 'yahoo.co.id', 'yahoo.fr', 'wanadoo.fr', 'rocketmail.com',
                 'club-internet.fr', 'juno.com', 'ig.com.br', 'live.co.uk', 'free.fr', 'yahoo.es', 'optusnet.com.au',
                 'windstream.net', 'hotmail.es', 'outlook.com', 'ntlworld.com', 'telenet.be', 'optonline.net',
                 'verizon.net', 'hotmail.it', 'sympatico.ca', 'cox.net', 'yahoo.ca', 'zonnet.nl', 'charter.net',
                 'aim.com', 'hotmail.com', 'live.it', 'tiscali.co.uk', 'tiscali.it', 'terra.com.br', 'comcast.net',
                 'uol.com.br', 'bigpond.com', 'yahoo.co.uk', 'freenet.de', 'frontiernet.net', 'yahoo.com.sg',
                 'planet.nl', 'yahoo.com', 'bol.com.br', 'hotmail.fr', 'centurytel.net', 'yahoo.com.ar', 'rambler.ru',
                 'me.com', 'googlemail.com', 'blueyonder.co.uk', 'web.de', 'chello.nl', 'shaw.ca', 'att.net', 'gmx.net',
                 'bluewin.ch', 'rediffmail.com', 'yahoo.com.mx', 'alice.it', 'yahoo.com.au', ]
