JOB_TITLES = ['molding utility worker', 'manager ambulatory', 'jack strip assembler', 'shift production supervisor',
              'telephone directory deliverer', 'prescription benefit specialist', 'furniture upholsterer apprentice',
              'fiber machine tender', 'consumer loan underwriter', 'malt specifications control assistant',
              'supervisor electrolytic tinning', 'it help desk analyst', 'orthotic and prosthetic technician',
              'sofa inspector', 'robotic welding operator', 'buckle attacher', 'valve mechanic',
              'dyeing machine back tender', 'nut dehydrator operator', 'cook cold meat', 'senior cost accountant',
              'fiction and nonfiction writer prose', 'x ray electronics wireman', 'wireless communications engineer',
              'button grader', 'instruction librarian', 'data quality consultant', 'magazine repairer',
              'garden machinery mechanic', 'bank boss', 'heat and frost insulator helper',
              'continuing education instructor', 'adjustment clerk', 'manager web', 'mining analyst',
              'lens block gauger', 'wind commissioning technician', 'biomed tech', 'datawarehouse developer',
              'asphalt tile floor layer', 'pile driving superintendent', 'cake puller',
              'automatic grinding machine operator', 'colorer machine', 'conservation science teacher',
              'machinist helper marine', 'theatre director', 'internet marketing manager', 'receiver bulk system',
              'computer systems designer', 'data base administrator', 'sausage inspector', 'cushion padder',
              'car jockey', 'entry level accounting clerk', 'seo team lead', 'curtain mender', 'sketcher',
              'refining machine operator', 'pricing intern', 'coil shaper', 'enamel pulverizer', 'climatology teacher',
              'rpg programmer analyst', 'assistant purchasing manager', 'roll builder', 'radio message router',
              'tank cooper', 'engineering program manager', 'sound technician', 'electro mechanical solar technician',
              'command and control specialist', 'physician scientist', 'acid strength inspector', 'sod farmer',
              'marklogic developer', 'ear muff assembler', 'header set up operator', 'admitting office escort',
              'rough planer tender', 'membership correspondent', 'non licensed nuclear plant operator',
              'supply crib attendant', 'technical services analyst', 'bus info consultant', 'middle school director',
              'commodity buyer', 'night guard', 'ink grinder', 'batteryman', 'shake backboard notcher',
              'pharmacology professor', 'picture enlarger', 'remote operations producer', 'acid dumper',
              'medical instructor', 'quality control lead', 'grout machine tender', 'director of student affairs',
              'reporter anchor', 'science intern', 'java systems analyst', 'mattress maker', 'aerial sprayer',
              'thermoscrew operator', 'antisqueak chalker', 'patient intake representative', 'teacher kindergarten',
              'guideman', 'packaging assembler', 'geriatric social worker', 'industrial maintenance mechanic',
              'casing tier', 'freight router', 'manager cafe', 'senior linux administrator', 'apiarist',
              'eyeglass lens grinder', 'ruby on rails web developer', 'housekeeping worker', 'mental hygienist',
              'naturalization examiner', 'client services administrator', 'tag and label cutter', 'manager procurement',
              'broadcast director operations', 'hypoid gear generator', 'perfume maker', 'validation specialist',
              'shear setter', 'weight guesser', 'supervisor long goods', 'workers compensation legal secretary',
              'electrical supervisor', 'apprentice lineman third step', 'concierge manager', 'brusher machine',
              'parachute marker', 'sales vendor', 'reverse unit operator', 'cupola repairer', 'ophthalmic pathologist',
              'automobile mechanic apprentice', 'x ray technician', 'iron cutter', 'photographic plate maker',
              'wheel lacer and truer', 'blackjack supervisor', 'museum attendant', 'clinical pharmacy technician',
              'slab grinder', 'steam tender', 'dairy farm supervisor', 'judicial registrar', 'area coordinator',
              'glass decorator', 'bike designer', 'rake operator', 'justice of the peace', 'contract mail carrier',
              'dish machine operator', 'media coordinator', 'compliance administrator', 'critical care paramedic',
              'compliance lead', 'hydraulic lift operator', 'painter ski edge', 'credit interviewer',
              'director of manufacturing operations', 'blindstitch machine operator', 'rnfa', 'boom cat operator',
              'treasury agent', 'spot checker', 'outsole compressor', 'client operations manager', 'counter cutter',
              'dope pourer', 'relocation commissioner', 'cargo router', 'salon supervisor', 'heat set operator',
              'employment recruiter', 'planer setter', 'stamp pad maker', 'salvage determiner',
              '911 emergency dispatcher', 'tube room cashier', 'foot caster', 'line worker', 'internet project manager',
              'quality measurement specialist', 'dietitian consultant', 'public administration professor',
              'glass fitter', 'manager of community relations', 'style advisor', 'aadc plans staff officer',
              'pelletizer tender', 'oil mixer', 'golf club facer', 'budget analyst', 'roofing applicator',
              'shuttle operator', 'charity fundraiser', 'sales financial analyst', 'project control analyst',
              'brewery worker', 'wall man', 'water vessel captain', 'furnace unloader', 'oncology nurse navigator',
              'replenishment merchandising associate', 'asset recovery specialist', 'video intern', 'tank carpenter',
              'cotton stripper', 'molding process technician', 'tax adjuster', 'auctioneer automobile',
              'bending shed worker', 'automatic oven operator', 'elevator repair mechanic', 'fluid jet cutter operator',
              'mat cleaning machine operator', 'medical receptionist assistant', 'mortgage originator',
              'orthodontist small business owner', 'environmental coordinator', 'ice cream freezer helper',
              'coal conveyor operator', 'egg crater', 'early childhood teacher', 'belt sander', 'culinary artist',
              'precision instrument maker and repairer', 'machine precision engraver', 'court reporter',
              'academic support coordinator', 'fuse assembler', 'herd tester', 'senior commissions analyst',
              'churn drill operator', 'tube man', 'network contract manager', 'transit mixer driver', 'latex caster',
              'manager architecture', 'cco & president', 'disintegrator', 'e learning developer',
              'biomedical engineering technician', 'middle school science teacher', 'electric fork operator',
              'cullet washer', 'dining room captain', 'reinsurance claims analyst', 'biomedical equipment tech',
              'logistics support', 'hoop punch operator helper', 'web master', 'lifeguard', 'call center director',
              'concrete precast moulder', 'funds transfer clerk', 'web marketing specialist', 'motorcycle maker',
              'solder making laborer', 'barrelhead inspector', 'combination saw operator', 'channel program manager',
              'manager commodities', 'outreach consultant', 'gravity prospecting operator', 'hydrologic engineer',
              'nailhead puncher', 'dip filler', 'forest pathology teacher', 'bistro attendant',
              'certified peer specialist', 'canal boat operator', 'aircraft motor mechanic', 'associate programmer',
              'assistant corporate controller', 'administrative staff supervisor', 'laboratory cureman',
              'angle shear operator', 'test equipment mechanic', 'anodize machine operator',
              'crystal growing technician', 'luggage liner', 'food processing chemist', 'customer support coordinator',
              'premium cancellation clerk', 'manager government', 'forestry professor', 'windows software developer',
              'quality liaison', 'commercial sales director', 'code enforcement supervisor', 'welding machine tender',
              'glassware verifier', 'staple processing machine operator', 'melter loader', 'deployment specialist',
              'industrial spraypainter', 'glue maker bone', 'dipping machine operator', 'drying supervisor',
              'leather scrubber', 'school resource officer', 'breaker up', 'tiller man', 'lab support tech',
              'hotel room attendant', 'box gluer', 'varnish inspector', 'event av operator', 'product ambassador',
              'sales secretary', 'gimp buttonhole machine operator', 'tailings worker', 'hr assistant',
              'president commercial bank', 'plant quality manager', 'hvac sheet metal installer helper',
              'glass cleaner', 'centrifuge separator operator', 'food safety field specialist', 'or director',
              'confectionery maker', 'diesel truck crane operator', 'bedspread inspector',
              'parenting skills instructor', 'automatic mold sander', 'safety and security officer',
              'superintendent logging', 'newspaper copy editor', 'logging specialist', 'wet end operator',
              'pega developer', 'knitting supervisor', 'steam conditioning operator', 'communications systems engineer',
              'greensman', 'billet straightener', 'billiard player', 'laundry routeman', 'quality cloth tester',
              'hydrographical technical officer', 'sap fico architect', 'product manager medical device',
              'barrel tester and drainer', 'trucker hand', 'engineering professor', 'radar signal processing engineer',
              'bonded structures repairer', 'care information associate', 'red hat linux administrator',
              'instructional consultant', 'finger cobbler', 'public health representative', 'kier hand',
              'hearing officer', 'master barber', 'jewel blocker and sawyer', 'screen printing machine loader unloader',
              'scale tank operator', 'fishing game warden', 'clinical team lead', 'recreation clerk',
              'shipyard painter helper', 'resistance brazer', 'seafood process worker', 'import coordinator',
              'rail filler', 'life sciences teacher', 'catalogue maker', 'natural resources technician',
              'awnings mechanic', 'consignee', 'law researcher', 'vp ad products and planning', 'shading painter',
              'insurance claims specialist', 'plow holder', 'autobody technician', 'supervisor nut processing',
              'porter bath', 'hardness inspector', 'stylist assistant', 'school secretary', 'inside barrel polisher',
              'acetaldehyde converter operator', 'airline transport pilot', 'news writer', 'security guard',
              'repair manager', 'senior strategy manager', 'clinical laboratory science professor', 'audit specialist',
              'material distributor', 'survey superintendent', 'hair or beauty salon manager', 'sand digger',
              'hourly associate', 'human services program specialist', 'stockroom inventory clerk',
              'airbrush artist photography', 'license inspector', 'steam frame operator', 'barrel header',
              'vendor representatives', 'tattoo and body artist', 'grades 1 thru 6 visiting teacher',
              'grinding machine tender', 'wind turbine controls engineer', 'supervisor body assembly', 'slubber hand',
              'stretch machine operator', 'school child care attendant', 'washer operator', 'live study manager',
              'auxiliary equipment tender', 'fashion marketer', 'client relations associate', 'recreation assistant',
              'lead java j2ee developer', 'health and fitness instructor', 'city superintendent of schools',
              'talent development consultant', 'heavy duty press operator', 'retail merchandiser technician',
              'donation specialist', 'lay out inspector', 'computer assistant', 'child care supervisor',
              'propulsion machinery service engineer', 'cordwood cutter', 'bss solution architect', 'esl instructor',
              'wolf hunter', 'net lead architect', 'reserves clerk', 'radio interference expert',
              'audio video technician', 'manager animal', 'reservations sales supervisor',
              'inorganic chemical technician', 'operations expert', 'cuff cutter', 'cut and print machine operator',
              'oven dumper', 'manager drive', 'sales analyst', 'printing sales representative', 'inker and opaquer',
              'test manager', 'breastfeeding educator', 'director of media', 'fruit bar maker',
              'laborer bituminous paving', 'sap technical architect', 'seam closer', 'mushroom grower',
              'regulatory internship', 'wildlife control operator', 'induction furnace operator', 'car carder',
              'loom fixer supervisor', 'accountant bookkeeper', 'yarn rewinder', 'coremaking machine setter',
              'successfactors consultant', 'head boys golf coach', 'sales and service engineer', 'senior teller',
              'manager quality systems', 'instructor correspondence school', 'process technician',
              'lamp stack developer', 'inspector golf ball', 'mover', 'business and marketing teacher', 'medicine tech',
              'weed sprayer', 'can filling machine operator', 'assembly hand', 'heel seat pounder',
              'residential direct support professional', 'volleyball referee', 'timekeeper',
              'botanical technical officer', 'boatbuilder wood', 'demonstrator sales', 'social research assistant',
              'band director', 'soda clerk', 'disability counselor', 'facing machine operator', ]
