from random import shuffle

FEMAILE_NAMES = ['Margret', 'Kat', 'Mada', 'Gabie', 'Shani', 'Susanne', 'Sascha', 'Romola', 'Arlyn', 'Georgette',
                 'Diena', 'Willamina', 'Shilpa', 'Ekaterina', 'Dale', 'Stella', 'Tarrah', 'Amalia', 'Hillary', 'Norene',
                 'Pen', 'Lorry', 'Selle', 'Ainslee', 'Yvette', 'Gunvor', 'Carrissa', 'Lil', 'Jobi', 'Marinna', 'Wally',
                 'Esta', 'Kristien', 'Mickie', 'Lynnette', 'Estele', 'Saree', 'Oralee', 'Marne', 'Jacquenette',
                 'Beverlee', 'Hellene', 'Loraine', 'Agna', 'Randi', 'Mehetabel', 'Leeann', 'Kym', 'Murielle',
                 'Delphine', 'Inga', 'Tracy', 'Lura', 'Carley', 'Bari', 'Claudine', 'Kirstyn', 'Mandy', 'Fleurette',
                 'Persis', 'Jessalyn', 'Delores', 'Berny', 'Gloria', 'Bev', 'Euphemia', 'Trude', 'Jerrilyn', 'Sylvie',
                 'Lindsey', 'Cecilla', 'Hyacinthie', 'Amata', 'Casia', 'Linda', 'Mallory', 'Ray', 'Jennee', 'Paola',
                 'Melisande', 'Kora', 'Julieta', 'Kaylyn', 'Lucita', 'Sandy', 'Saba', 'Tamarra', 'Felecia', 'Jenine',
                 'Krystal', 'Laura', 'Viviana', 'Ferdinande', 'Gera', 'Arliene', 'Audie', 'Sean', 'Verene', 'Rebeka',
                 'Emanuela', 'Isabel', 'Edi', 'Shanda', 'Corrine', 'Marlane', 'Romy', 'Charlena', 'Mellisa', 'Lillian',
                 'Catlin', 'Guenevere', 'Merrie', 'Shayne', 'Kimberley', 'Margaretha', 'Georgiana', 'Natka', 'Wenonah',
                 'Celesta', 'Verina', 'Mirabella', 'Zaneta', 'Agnola', 'Trina', 'Jude', 'Gilberte', 'Tiff', 'Trudy',
                 'Leticia', 'Ardelis', 'Ellen', 'Marrissa', 'Marnie', 'Onlea', 'Arly', 'Sophi', 'Alice', 'Ayn',
                 'Katusha', 'Gusti', 'Loralie', 'Kathleen', 'Chanda', 'Davine', 'Binni', 'Emmy', 'Erina', 'Shaine',
                 'Rosamund', 'Tootsie', 'Rheta', 'Carlie', 'Lindi', 'Allyce', 'Bamby', 'Lou', 'Krystyna', 'Nichole',
                 'Katerina', 'Karissa', 'Rorie', 'Larina', 'Karly', 'Rosette', 'Barbi', 'Zitella', 'Fleur', 'Issie',
                 'Jocelyn', 'Kacey', 'Berna', 'Yetta', 'Maribel', 'Emalia', 'Dianna', 'Daisie', 'Annabelle', 'Rivy',
                 'Dafna', 'Jayne', 'Sunny', 'Sharity', 'Isis', 'Barbabra', 'Buffy', 'Phoebe', 'Deni', 'Ameline', 'Cody',
                 'Ebba', 'Janot', 'Elli', 'Codee', 'Jean', 'Starlin', 'Camella', 'Lucia', 'Tori', 'Valery', 'Phaidra',
                 'Eileen', 'Malva', 'Anette', 'Lusa', 'Giana', 'Sonny', 'Ramonda', 'Loreen', 'Harriott', 'Sapphire',
                 'Calley', 'Dyanna', 'Sheri', 'Angele', 'Bettine', 'Kare', 'Nova', 'Umeko', 'Clovis', 'Jobey',
                 'Millicent', 'Pattie', 'Annelise', 'Amanda', 'Norean', 'Illa', 'Irita', 'Juana', 'Alana', 'Julissa',
                 'Dona', 'Brittan', 'Deeanne', 'Zsa Zsa', 'Saudra', 'Isabeau', 'Elizabeth', 'Crissie', 'Danit',
                 'Zuzana', 'Xylina', 'Annette', 'Dinny', 'Ida', 'Carla', 'Briteny', 'Paula-Grace', 'Amber', 'Merilyn',
                 'Gabbey', 'Jemimah', 'Opalina', 'Kerry', 'Anne', 'Sharl', 'Rozina', 'Silvie', 'Michelina', 'Leia',
                 'Corabel', 'Maressa', 'Eba', 'Bridget', 'Mellicent', 'Mel', 'Kimmie', 'Suzette', 'Bernadene', 'Audi',
                 'Rubina', 'Morgana', 'Blanche', 'Florinda', 'Andrea', 'Flore', 'Joscelin', 'Ruella', 'Hedy',
                 'Cassandry', 'Georgine', 'Philis', 'Melosa', 'Bird', 'Denyse', 'Karolina', 'Celina', 'Kristel',
                 'Tansy', 'Antonella', 'Renee', 'Bell', 'Damita', 'Flor', 'Lane', 'Ora', 'Elizabet', 'Harmonie',
                 'Rikki', 'Andriette', 'Beverie', ]

MALE_NAMES = ['Byron', 'Andie', 'Josiah', 'Hershel', 'Sherlocke', 'Laurens', 'Curtice', 'Fitz', 'Warde', 'Demetre',
              'Marlowe', 'Thor', 'Thaddeus', 'Davidson', 'Fletcher', 'Pearce', 'Roderic', 'Maxfield', 'Austen',
              'Colin', 'Gerold', 'Pennie', 'Rockwell', 'Elihu', 'Stearne', 'Herrmann', 'Amadeus', 'Web', 'Skipp',
              'Brice', 'Janus', 'Jose', 'Lyle', 'Devin', 'Domenic', 'Olin', 'Elvis', 'Prescott', 'Verney', 'Town',
              'Barri', 'Zerk', 'Kimball', 'Neville', 'Franklyn', 'Elton', 'Swen', 'Irvine', 'Evelyn', 'Wyatan',
              'Laird', 'Norris', 'Eustace', 'Adlai', 'Dimitrou', 'Berchtold', 'Lukas', 'Dominic', 'Berkley',
              'Archie', 'Ernst', 'Lazlo', 'Zedekiah', 'Normie', 'Worthington', 'Elwood', 'Emmet', 'Emerson', 'Brad',
              'Graig', 'Montague', 'Giuseppe', 'Darian', 'Zachery', 'Chance', 'Gabriello', 'Wang', 'Herbie',
              'Scotty', 'Tomkin', 'Troy', 'Sholom', 'Quintin', 'Harvie', 'Chrissy', 'Nathanil', 'Tracy', 'Durward',
              'Abdul', 'Bruce', 'Aguinaldo', 'Harley', 'Noach', 'Sylvan', 'Traver', 'Wiatt', 'Pincus', 'Berk',
              'Chadwick', 'Freeman', 'Claude', 'Lay', 'Sly', 'Jodie', 'Marlow', 'Penn', 'Zippy', 'Ulric', 'Zack',
              'Armstrong', 'Ned', 'Tarrant', 'Fox', 'Thorsten', 'Hillel', 'Alexander', 'Brooke', 'Alejandro',
              'Carlyle', 'Pincas', 'Kalman', 'Quinton', 'Hamlet', 'Brendan', 'Blake', 'Vincent', 'Wolfram', 'Taber',
              'Izak', 'Arvind', 'Davey', 'Ebenezer', 'Harv', 'Lennie', 'Salvador', 'Tobie', 'Nunzio', 'Jermain',
              'Hartley', 'Giff', 'Rainer', 'Royal', 'Shawn', 'Trever', 'Lane', 'Christof', 'Vinny', 'Van', 'Juergen',
              'Johnnie', 'Benn', 'Jake', 'Alastair', 'Horacio', 'Doyle', 'Spence', 'Forrest', 'Purcell', 'Jennings',
              'Bailie', 'Lenard', 'Rudolf', 'Emory', 'Milt', 'Bartholemy', 'Neddy', 'Neale', 'Paddy', 'Arvy',
              'Adrick', 'Reynold', 'Griswold', 'Virgie', 'Skip', 'Scottie', 'Richard', 'Regen', 'Trey', 'Guthrie',
              'Prince', 'Ethan', 'Desmond', 'Morton', 'Ransell', 'Alan', 'Erick', 'Clemmie', 'Winthrop', 'Doug',
              'Rajeev', 'Hermon', 'Ravil', 'Dimitrios', 'Wait', 'Giacomo', 'Saunderson', 'Artur', 'Keil', 'Holly',
              'Reynard', 'Denis', 'Douglass', 'Westleigh', 'Carlton', 'Clair', 'Joshua', 'Othello', 'Hale', 'Sam',
              'Norman', 'Torr', 'Odie', 'Finley', 'Bo', 'Fazeel', 'Gayle', 'Alasdair', 'Merv', 'Tedie', 'Nahum',
              'Kendrick', 'Uli', 'Freddie', 'Bradly', 'Filipe', 'Rodd', 'Mylo', 'Mikael', 'Percy', 'Haywood',
              'Mordecai', 'Waverly', 'Gilbert', 'Stanley', 'Dunstan', 'Reuven', 'Ulrick', 'Thornie', 'Jeffie',
              'Merlin', 'Jean-Marc', 'Avram', 'Fraser', 'Torrence', 'Brooks', 'Lindsey', 'Chaunce', 'Barbabas',
              'Niall', 'Kingsley', 'Rocky', 'Ichabod', 'Hewitt', 'Gearard', 'Shaine', 'Muffin', 'Rolland', 'Edgardo',
              'Foster', 'Rog', 'Chariot', 'Garcia', 'Luis', 'Darrel', 'Ev', 'Darien', 'Barron', 'Whitaker', 'Josh',
              'Piggy', 'Leighton', 'Inglebert', 'Norwood', 'Lancelot', 'Selby', 'Olivier', 'Fredrick', 'Adolphus',
              'Martino', 'Hendrick', 'Dillon', 'Gamaliel', 'Rudolph', 'Noble', 'Valentin', 'Harlin', 'Alphonso',
              'Emmett', 'Prentiss', 'Nate', 'Frederick', 'Waylan', 'Geoffrey', 'Rudy', 'Otto', 'Fabian', 'Ruben',
              'Kellen', 'Gill', 'Ricki', ]

LAST_NAMES = ['Pope', 'Beltran', 'Marsh', 'Beck', 'Wilson', 'Leach', 'Clark', 'Nunez', 'Cisneros', 'Valdez', 'Moreno',
              'Finley', 'Frye', 'Hutchinson', 'Norton', 'Walker', 'Paul', 'Reid', 'Rivas', 'Francis', 'Brennan', 'Mata',
              'Arnold', 'Chandler', 'Lyons', 'Callahan', 'Arias', 'Olsen', 'Cantu', 'Li', 'Curry', 'Berg', 'Wiley',
              'Mathis', 'Ventura', 'Bernard', 'Melton', 'Pitts', 'Koch', 'Higgins', 'Escobar', 'Pace', 'Mosley',
              'Matthews', 'May', 'Robles', 'Hood', 'Sosa', 'Perry', 'Howard', 'Glenn', 'Savage', 'Gentry', 'Clayton',
              'Rubio', 'Perez', 'Mayo', 'Day', 'Roach', 'Livingston', 'Craig', 'Pugh', 'Morrison', 'Trujillo',
              'Stanton', 'Greene', 'Pruitt', 'Heath', 'Johns', 'Collins', 'Daniels', 'Hail', 'Yang', 'Brewer',
              'Nichols', 'Moore', 'Barnett', 'Nielsen', 'Monroe', 'Newman', 'Cortes', 'English', 'Berry', 'Fletcher',
              'Clements', 'Reed', 'Howell', 'Bass', 'Perkins', 'Jacobson', 'Baldwin', 'Montoya', 'Peterson', 'Hayes',
              'Bradley', 'Williamson', 'Contreras', 'Banks', 'Chang', 'Norman', 'Terry', 'Freeman', 'Armstrong', 'Orr',
              'Dunn', 'Morrow', 'Leonard', 'Palmer', 'Rollins', 'Lam', 'Adams', 'Douglas', 'Baker', 'Hampton',
              'Estrada', 'Pennington', 'Enriquez', 'Ray', 'Dougherty', 'Lozano', 'Lynn', 'Martinez', 'Barry', 'Lawson',
              'Cameron', 'Osborne', 'Davila', 'Hodges', 'Lamb', 'Dennis', 'Guerrero', 'Holland', 'Reyna', 'Ward',
              'Jenkins', 'Ayala', 'Ayers', 'Fernandez', 'Fuentes', 'West', 'Steele', 'Potter', 'Smith', 'Kerr',
              'Barrera', 'Moses', 'Townsend', 'Young', 'Fischer', 'Hunter', 'Booker', 'Fowler', 'Cummings', 'Shields',
              'Lang', 'Hartman', 'Branch', 'Pratt', 'Crawford', 'Sullivan', 'Lindsey', 'Lewis', 'Everett', 'Villegas',
              'Farley', 'Quintana', 'Padilla', 'Bowman', 'Pacheco', 'Blackburn', 'Jennings', 'Bravo', 'Lambert',
              'Fitzpatrick', 'Carey', 'Velasquez', 'Spears', 'Vincent', 'Castillo', 'Meyer', 'Bowers', 'Mcmahon',
              'Stephens', 'Hardy', 'Maxwell', 'Holmes', 'Schneider', 'Knox', 'Blankenship', 'Erickson', 'Franco',
              'Miller', 'Trevino', 'Holt', 'Briggs', 'Fry', 'Welch', 'Knapp', 'Ryan', 'Portillo', 'Mccoy', 'Walters',
              'Gallagher', 'Carson', 'Blackwell', 'Espinosa', 'Guerra', 'Solis', 'Obrien', 'Shah', 'Wallace', 'Casey',
              'Owens', 'Gonzales', 'Macdonald', 'Potts', 'Wiggins', 'Fuller', 'Ramirez', 'Weber', 'Powers', 'Hale',
              'Peralta', 'Aguilar', 'Kline', 'Luna', 'Alfaro', 'Morse', 'Gutierrez', 'Riley', 'Jacobs', 'King',
              'Santos', 'Mcclure', 'Oneal', 'Mcintosh', 'Guevara', 'Middleton', 'Mays', 'Clay', 'Mack', 'S', 'Becker',
              'Wise', 'Stout', 'Norris', 'Bennett', 'Oliver', 'Andersen', 'Morton', 'Wade', 'Krueger', 'Valentine',
              'Randall', 'Harper', 'Navarro', 'Warner', 'Hahn', 'Mcmillan', 'Rowe', 'Mendoza', 'Atkinson', 'Fitzgerald',
              'Chase', 'Mitchell', 'Burgess', 'Barajas', 'Valenzuela', 'Mcpherson', 'Fisher', 'David', 'Sheppard',
              'Eaton', 'Woodard', 'Webster', 'House', 'Dillon', 'Pierce', 'Elliott', 'Garner', 'Nixon', 'Choi',
              'Vargas', 'Tyler', 'Ferguson', 'Conrad', 'Arroyo', 'Strickland', 'Yates', 'Andrews', 'Larson', 'Mendez',
              'Adkins', 'S', 'Delacruz', 'Ellison', 'Rangel', 'Lim', 'Hurley', 'Reeves', ]
